version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 3
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/" # even for `.github/workflows`
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"