services:
  cryptomator-docs:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./source:/source
      - ./build:/build
    command: >
      sphinx-autobuild
      -b dirhtml
      /source
      /build/dirhtml
      --host 0.0.0.0
